// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Bebas_Neue, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

// 1. Configure the "Jersey Number" Font (Headings)
const bebas = Bebas_Neue({ 
  weight: "400", 
  subsets: ["latin"],
  variable: "--font-bebas" 
});

// 2. Configure the "Body" Font (Reading Text)
const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter" 
});

// 3. SEO Metadata
export const metadata: Metadata = {
  title: "Virat Kohli | The King's Arena",
  description: "An immersive 3D experience celebrating the G.O.A.T of Cricket.",
  icons: {
    icon: "/favicon.ico", // Ensure you have a favicon in public/ later
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* We inject the font variables into the body.
        'antialiased' makes the text look sharp on 3D backgrounds.
      */}
      <body className={cn(
        bebas.variable, 
        inter.variable, 
        "antialiased bg-vk-black text-white overflow-hidden"
      )}>
        {children}
      </body>
    </html>
  );
}